--FERNANDO_CAMIRAN

--CRIANDO SEQUENCIA
  CREATE SEQUENCE MUN_ID START WITH 1 INCREMENT BY 1;
  CREATE SEQUENCE BAI_ID START WITH 1 INCREMENT BY 1;
  CREATE SEQUENCE END_ID START WITH 1 INCREMENT BY 1;
  CREATE SEQUENCE CLI_ID START WITH 1 INCREMENT BY 1;
  CREATE SEQUENCE FUN_ID START WITH 1 INCREMENT BY 1;
  CREATE SEQUENCE FIL_ID START WITH 1 INCREMENT BY 1;
  CREATE SEQUENCE GEN_ID START WITH 1 INCREMENT BY 1;
  CREATE SEQUENCE VEND_ID START WITH 1 INCREMENT BY 1;

--INSERT NAS TABELAS

-- TB_MUNICIPIO
  INSERT INTO TB_MUNICIPIO (MUN_ID, MUN_DESCRICAO)
        VALUES (MUN_ID.NEXTVAL, 'SOROCABA');
  
  INSERT INTO TB_MUNICIPIO (MUN_ID, MUN_DESCRICAO)
        VALUES (MUN_ID.NEXTVAL, 'MEDIANEIRA');
  INSERT INTO TB_MUNICIPIO (MUN_ID, MUN_DESCRICAO)
        VALUES (MUN_ID.NEXTVAL, 'CASCAVEL');
  
-- TB_BAIRRO
    INSERT INTO TB_BAIRRO(BAI_ID, BAI_DESCRICAO, MUN_ID)
          VALUES(BAI_ID.NEXTVAL, 'CENTRO', 1);  
          
    INSERT INTO TB_BAIRRO(BAI_ID, BAI_DESCRICAO, MUN_ID)
          VALUES(BAI_ID.NEXTVAL, 'CENTRO', 2);  
    INSERT INTO TB_BAIRRO(BAI_ID, BAI_DESCRICAO, MUN_ID)
          VALUES(BAI_ID.NEXTVAL, 'CIDADE ALTA', 2);  
    INSERT INTO TB_BAIRRO(BAI_ID, BAI_DESCRICAO, MUN_ID)
          VALUES(BAI_ID.NEXTVAL, 'INDEPENDENCIA', 2);  
    INSERT INTO TB_BAIRRO(BAI_ID, BAI_DESCRICAO, MUN_ID)
          VALUES(BAI_ID.NEXTVAL, 'COUNTRY', 3);  
          
--TB_ENDERECO
  INSERT INTO TB_ENDERECO(END_ID, END_DESCRICAO, BAI_ID)
        VALUES (END_ID.NEXTVAL, 'RUA MATO GROSSO', 3);
  INSERT INTO TB_ENDERECO(END_ID, END_DESCRICAO, BAI_ID)
        VALUES (END_ID.NEXTVAL, 'RUA IPES', 2);     
  INSERT INTO TB_ENDERECO(END_ID, END_DESCRICAO, BAI_ID)
        VALUES (END_ID.NEXTVAL, 'AVENIDA LIBERDADE', 5);
  INSERT INTO TB_ENDERECO(END_ID, END_DESCRICAO, BAI_ID)
        VALUES (END_ID.NEXTVAL, 'RUA WASHINGTON', 4);
  INSERT INTO TB_ENDERECO(END_ID, END_DESCRICAO, BAI_ID)
        VALUES (END_ID.NEXTVAL, 'AVENIDA MADRI', 1);
  INSERT INTO TB_ENDERECO(END_ID, END_DESCRICAO, BAI_ID)
        VALUES (END_ID.NEXTVAL, 'RUA OLIVEIRAS', 3);
  INSERT INTO TB_ENDERECO(END_ID, END_DESCRICAO, BAI_ID)
        VALUES (END_ID.NEXTVAL, 'RUA ELEVADA', 2);
  INSERT INTO TB_ENDERECO(END_ID, END_DESCRICAO, BAI_ID)
        VALUES (END_ID.NEXTVAL, 'AVENIDA PRATEADA', 3);
  
-- TB_CLIENTE
  INSERT INTO TB_CLIENTE(CLI_ID, CLI_NOME, CLI_CPF, CLI_RG, CLI_TELEFONE, CLI_DT_NASCIMENTO, CLI_END_ID)
        VALUES(CLI_ID.NEXTVAL, 'João Marcos', '95738271647', '73849217', '66458947893', TO_DATE('1995-03-08', 'YYYY-MM-DD'), 5);
  INSERT INTO TB_CLIENTE(CLI_ID, CLI_NOME, CLI_CPF, CLI_RG, CLI_TELEFONE, CLI_DT_NASCIMENTO, CLI_END_ID)
        VALUES (CLI_ID.NEXTVAL, 'Carlos Silva', '12345678901', '11223344', '98123456789', TO_DATE('1990-07-15', 'YYYY-MM-DD'), 1);
  INSERT INTO TB_CLIENTE(CLI_ID, CLI_NOME, CLI_CPF, CLI_RG, CLI_TELEFONE, CLI_DT_NASCIMENTO, CLI_END_ID)
        VALUES (CLI_ID.NEXTVAL, 'Ana Souza', '98765432100', '55667788', '99987654321', TO_DATE('1985-11-20', 'YYYY-MM-DD'), 2);
  INSERT INTO TB_CLIENTE(CLI_ID, CLI_NOME, CLI_CPF, CLI_RG, CLI_TELEFONE, CLI_DT_NASCIMENTO, CLI_END_ID)
        VALUES (CLI_ID.NEXTVAL, 'Ricardo Almeida', '78945612300', '66778899', '91765432100', TO_DATE('1993-02-28', 'YYYY-MM-DD'), 3);
  INSERT INTO TB_CLIENTE(CLI_ID, CLI_NOME, CLI_CPF, CLI_RG, CLI_TELEFONE, CLI_DT_NASCIMENTO, CLI_END_ID)
        VALUES (CLI_ID.NEXTVAL, 'Maria Costa', '32165498700', '22334455', '99876543210', TO_DATE('1988-12-05', 'YYYY-MM-DD'), 4);
  
-- TB_FUNCIONARIO
  INSERT INTO TB_FUNCIONARIO(FUN_ID, FUN_NOME, FUN_CPF, FUN_RG, FUN_TELEFONE, FUN_SALARIO, FUN_END_ID)
        VALUES(FUN_ID.NEXTVAL, 'JULIO CEZAR', '85745342187', '56473829', '12355793', 3200.50, 8);
  INSERT INTO TB_FUNCIONARIO(FUN_ID, FUN_NOME, FUN_CPF, FUN_RG, FUN_TELEFONE, FUN_SALARIO, FUN_END_ID)
        VALUES(FUN_ID.NEXTVAL, 'MARIA LIMA', '98765432100', '33445566', '98765432100', 3500.75, 7);
  INSERT INTO TB_FUNCIONARIO(FUN_ID, FUN_NOME, FUN_CPF, FUN_RG, FUN_TELEFONE, FUN_SALARIO, FUN_END_ID)
        VALUES(FUN_ID.NEXTVAL, 'CARLOS EDUARDO', '12345678901', '11223344', '98712345678', 2800.00, 6);
        
-- TB_GENERO
  INSERT INTO TB_GENERO(GEN_ID, GEN_DESCRICAO)
        VALUES (GEN_ID.NEXTVAL, 'COMÉDIA');
  INSERT INTO TB_GENERO(GEN_ID, GEN_DESCRICAO)
        VALUES (GEN_ID.NEXTVAL, 'TERROR');
  INSERT INTO TB_GENERO(GEN_ID, GEN_DESCRICAO)
        VALUES (GEN_ID.NEXTVAL, 'AÇÃO');
  INSERT INTO TB_GENERO(GEN_ID, GEN_DESCRICAO)
        VALUES (GEN_ID.NEXTVAL, 'SUSPENSE');
  INSERT INTO TB_GENERO(GEN_ID, GEN_DESCRICAO)
        VALUES (GEN_ID.NEXTVAL, 'FICÇÃO CIENTÍFICA');
  
        SELECT * FROM TB_GENERO; 

-- TB_FILME
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 1, 'BABÁ MCPHEE', 97, 3);  
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 3, 'A HORA DO RUSH', 98, 2); 
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 5, 'MATRIX', 136, 4);      
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 4, 'O POÇO', 94, 1);      
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 2, 'IT', 135, 1);      
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 1, 'AS BRANQUELAS', 109, 2);
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 2, 'INVOCAÇÃO DO MAL', 112, 2);
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 3, 'JHON WICK', 101, 2);
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 5, 'INTERESTELAR', 169, 2);
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 5, 'BLADE RUNNER 2049', 164, 3);
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 2, 'ATIVIDADE PARANORMAL', 86, 1);
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 1, 'DEBI E LÓIDE', 107, 3);
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 1, 'SE BEBER, NÃO CASE!', 100, 4);
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
        VALUES (FIL_ID.NEXTVAL, 5, 'A ORIGEM', 148, 1);
  INSERT INTO TB_FILME(FIL_ID, FIL_CODGENERO, FIL_NOME, FIL_TEMP, FIL_QUANT)
      VALUES (FIL_ID.NEXTVAL, 4, 'CISNE NEGRO', 108, 3);
      
  SELECT * FROM TB_FILME;
      
 -- TB_VENDA
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2022-12-07','YYYY-MM-DD'), 100.75, 1, 3);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2023-10-02','YYYY-MM-DD'), 200.30, 3, 2);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2024-02-20','YYYY-MM-DD'), 150.60, 2, 1);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2025-01-10','YYYY-MM-DD'), 60.50, 4, 2);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2025-08-28','YYYY-MM-DD'), 120.00, 5, 3);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2022-11-15','YYYY-MM-DD'), 250.90, 2, 1);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2022-10-03','YYYY-MM-DD'), 175.30, 3, 2);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2023-09-18','YYYY-MM-DD'), 320.50, 4, 1);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2023-07-25','YYYY-MM-DD'), 95.60, 5, 3);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2024-03-10','YYYY-MM-DD'), 180.90, 1, 2);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2024-05-05','YYYY-MM-DD'), 220.75, 4, 3);
  INSERT INTO TB_VENDA(VEND_ID, VEND_DATA, VEND_VALOR, VEND_CLI_ID, VEND_FUN_ID)
        VALUES (VEND_ID.NEXTVAL, TO_DATE('2025-06-15','YYYY-MM-DD'), 340.80, 3, 1);
 SELECT * FROM TB_VENDA;

-- TB_VENDA_FILME
-- CORRIGINDO FALTA DE PRIMARY KEY
ALTER TABLE TB_VENDA_FILME
ADD CONSTRAINT PK_VENDA_FILME PRIMARY KEY (VEND_ID, FIL_ID);
SELECT * FROM TB_VENDA_FILME;

--INSERT TB_VENDA_FILME
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (14, 1, 40.00);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (14, 2, 30.75);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (14, 3, 30.00);
        
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (2, 13, 80.00);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (2, 9, 70.30);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (2, 8, 50.00);
   
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (3, 11, 75.30);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (3, 7, 75.30);  

  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (4, 12, 60.50);

  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (5, 2, 60.00);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (5, 4, 60.00);

  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (6, 6, 90.90);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (6, 10, 80.00);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (6, 5, 80.00);

  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (7, 1, 75.30);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (7, 10, 100.00);

  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (8, 2, 120.50);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (8, 3, 100.00);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (8, 6, 100.00);

  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (9, 3, 50.60);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (9, 7, 45.00);

  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (10, 2, 100.90);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (10, 5, 80.00);

  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (11, 6, 120.75);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (11, 1, 100.00);

  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (12, 9, 140.80);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (12, 1, 100.00);
  INSERT INTO TB_VENDA_FILME(VEND_ID, FIL_ID, VF_VALOR) VALUES (12, 4, 100.00);
  