--SYSTEM
-- criando a base de dados

CREATE TABLESPACE analistadedados
DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\analistadedados.dbf'
SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 500M
ONLINE 
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;


--CRIAR USUÁRIO 

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER FERNANDO_CAMIRAN IDENTIFIED BY sql
DEFAULT TABLESPACE analistadedados
TEMPORARY TABLESPACE temp;

-- ROLES E PERMISSÕES 

CREATE ROLE ACESSO_LV1;

GRANT SELECT ANY TABLE TO  ACESSO_LV1;
GRANT CONNECT TO  ACESSO_LV1;
GRANT ALTER SESSION TO  ACESSO_LV1;
GRANT CREATE SESSION TO  ACESSO_LV1;
GRANT EXECUTE ANY PROCEDURE TO  ACESSO_LV1;

CREATE ROLE ACESSO_LV2;
GRANT ACESSO_LV1 TO ACESSO_LV2;
GRANT INSERT ANY TABLE TO ACESSO_LV2;
GRANT UPDATE ANY TABLE TO ACESSO_LV2;
GRANT DELETE ANY TABLE TO ACESSO_LV2;
GRANT SELECT ANY SEQUENCE TO ACESSO_LV2;

CREATE ROLE ACESSO_LV3;
GRANT ACESSO_LV2 TO ACESSO_LV3;
GRANT CREATE ANY TABLE TO ACESSO_LV3;
GRANT CREATE ANY TRIGGER TO ACESSO_LV3;
GRANT CREATE ANY VIEW TO ACESSO_LV3;
GRANT CREATE ANY PROCEDURE TO ACESSO_LV3;
GRANT CREATE ANY SEQUENCE TO ACESSO_LV3;

GRANT DROP ANY TABLE TO ACESSO_LV3;
GRANT DROP ANY TRIGGER TO ACESSO_LV3;
GRANT DROP ANY VIEW TO ACESSO_LV3;
GRANT DROP ANY PROCEDURE TO ACESSO_LV3;
GRANT DROP ANY SEQUENCE TO ACESSO_LV3;

GRANT ACESSO_LV3 TO FERNANDO_CAMIRAN;

--mudando a role default e deixando sem restrições
ALTER USER FERNANDO_CAMIRAN DEFAULT ROLE ACESSO_LV3;
ALTER USER FERNANDO_CAMIRAN QUOTA UNLIMITED ON ANALISTADEDADOS;
